shared:
    image: centos
    
parameters:
    region: "us-west-1"
    az:
        value: "false"
        description: "default availability zone"
    cluster: ["cluster1", "cluster2"]

jobs:
    A:
        requires: [~commit]
        steps: 
            - step2: |
                if [[ "$(meta get parameters.az.value)" == true ]]; then
                    sleep 21; echo in parallel
                else
                    sleep 20; echo1 in parallel
                fi
    B:
        requires: [~commit]
        steps:
            - StepB: sleep 10; echo in parallel
    C:
        requires: [A, B]
        steps:
            - stepC: echo join after A and B
            
    D:
        requires: [A, B]
        steps:
            - stepD: echo join after A and B
            
    E:
        requires: [B]
        steps:
            - stepE: echo join after A and B
            
