shared:
    image: node:14

jobs:
    A:
        requires: [~commit]
        steps:
            - echo1: sleep 10;echo in parallel
    B:
        requires: [~commit]
        steps:
            - echo: sleep 5;echo1 in parallel
    C:
        requires: [A, B]
        steps:
            - echo: echo join after A and B
